// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddressAutocompleteController from "./address_autocomplete_controller"
application.register("address-autocomplete", AddressAutocompleteController)

import CharcountController from "./charcount_controller"
application.register("charcount", CharcountController)

import ConversationSubscriptionController from "./conversation_subscription_controller"
application.register("conversation-subscription", ConversationSubscriptionController)

import FaqButtonsController from "./faq_buttons_controller"
application.register("faq-buttons", FaqButtonsController)

import FlatpickrController from "./flatpickr_controller"
application.register("flatpickr", FlatpickrController)

import MapController from "./map_controller"
application.register("map", MapController)

import PhotoPreviewController from "./photo_preview_controller"
application.register("photo-preview", PhotoPreviewController)

import QuantitySpinnerController from "./quantity_spinner_controller"
application.register("quantity-spinner", QuantitySpinnerController)

import ToggleGardenProductsController from "./toggle_garden_products_controller"
application.register("toggle-garden-products", ToggleGardenProductsController)

import TogglePasswordVisibilityController from "./toggle_password_visibility_controller"
application.register("toggle-password-visibility", TogglePasswordVisibilityController)

import TomSelectController from "./tom_select_controller"
application.register("tom-select", TomSelectController)
